- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check vars
      ansible.builtin.assert:
        that:
          - nfs_server_ip is defined 
          - nfs_server_path is defined 
        fail_msg: "Error: VARS 'nfs_server_ip' or 'nfs_server_path' are not defined."
      run_once: true
    - name: install nfs-utils
      ansible.builtin.dnf:
        name: nfs-utils
        state: present
    - name: mount nfs
      ansible.posix.mount:
        src: "{{ nfs_server_ip }}:{{ nfs_server_path }}"
        path: /mnt/nfs_share
        opts: ro,sync,hard,intr
        fstype: nfs
        state: mounted
    - name: ls nfs_share
      ansible.builtin.command:
        cmd: "ls -al /mnt/nfs_share/work_dir"
        register: mount_ls
    - name: output ls
      ansible.builtin.debug:
        msg: "{{ mount_ls.stdout_lines }}"
    - name: unmount nfs
      ansible.posix.mount:
        src: "{{ nfs_server_ip }}:{{ nfs_server_path }}"
        path: /mnt/nfs_share
        fstype: nfs
        state: absent